#!/bin/bash

echo "📧 Gmail API Setup Verification"
echo ""
echo "🔗 Direct link to enable Gmail API:"
echo "   https://console.developers.google.com/apis/api/gmail.googleapis.com/overview?project=300010916290"
echo ""
echo "📋 Manual steps:"
echo "1. Go to Google Cloud Console"
echo "2. Select project: mailscribe-ae722"
echo "3. Go to APIs & Services > Library"
echo "4. Search 'Gmail API' and click Enable"
echo ""
echo "⏱️  After enabling:"
echo "- Wait 2-3 minutes for propagation"
echo "- Test email search in MailScribe again"
echo ""
echo "🔍 Verify setup:"
echo "- APIs & Services > Enabled APIs"
echo "- Should see 'Gmail API' in the list"
echo ""
echo "🔐 If you get permission errors:"
echo "- APIs & Services > OAuth consent screen"
echo "- Add your email as test user"
echo "- Verify Gmail scopes are included"
echo ""
